site_name: OpenIoT 开源IoT
repo_url: https://github.com/whsheng/openiot_blog
copyright: Copyright © 2019 Mr.Wang 粤ICP备19007213号-1
pages:
  - [index.md,Home]
  - [iot.md,IoT]
  - [ai.md,AI]
  - [5g.md,5G]
  - [about.md,About]

#theme: readthedocs
