site_name: OpenIoT 开源IoT
repo_url: https://github.com/whsheng/openiot_blog
copyright: Copyright © 2019 Mr.Wang <a href="http://beian.miit.gov.cn"> 粤ICP备19007213号-1
nav: 
  - Home: index.md
  - IoT: iot.md
  - AI: ai.md
  - 5G: 5g.md
  - About: about.md

#theme: readthedocs
